[package]
name = "hostmonitoring-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Web server framework
axum = { version = "0.6.2", features = ["headers"] }
# Cli library
blarg = "0.2.1"
# Async runtime library
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
